#!/bin/sh

#--------------------------------------------------------------------[ KEYMAP ]-

setup-keymap us us

#-------------------------------------------------------------------[ NETWORK ]-

mkdir -p /etc/udhcpc
printf 'alpine\n'           > /etc/hostname
printf 'RESOLV_CONF="no"\n' > /etc/udhcpc/udhcpc.conf

cat <<__HOSTS__  > /etc/hosts
127.0.0.1	alpine.localdomain alpine
::1		alpine.localdomain alpine
__HOSTS__

cat <<__RESOLV_CONF__ > /etc/resolv.conf
nameserver 9.9.9.9
nameserver 1.1.1.1
__RESOLV_CONF__

rc-service hostname restart

setup-interfaces

WPA_CONF_FILE='/etc/wpa_supplicant/wpa_supplicant.conf'

sed -i '
1i ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wheel
1i update_config=1
' "${WPA_CONF_FILE}"

rc-update add networking boot && rc-service networking start
rc-update add seedrng    boot && rc-service seedrng    start

#------------------------------------------------------------------[ PACKAGES ]-

setup-apkrepos -f

sed -i  -e 's%^#%%g' \
        -e 's%^\/media%#\0%g' /etc/apk/repositories

apk -q add tzdata acpid acpid-openrc zzz cfdisk lsblk

#-----------------------------------------------------------------------[ NTP ]-

install -Dm 0644 /usr/share/zoneinfo/Asia/Kolkata /etc/zoneinfo/Asia/Kolkata

cat <<EOF >> /etc/profile.d/timezone.sh
export TZ='${TZ:-Asia/Kolkata}'
EOF

. /etc/profile.d/timezone.sh

setup-ntp busybox

#----------------------------------------------------------------------[ ACPI ]-

rc-update add acpid && rc-service acpid start

#--------------------------------------------------------------------[ PASSWD ]-

passwd root
