#!/bin/sh

#------------------------------------------------------------------[ PACKAGES ]-

apk add efibootmgr grub-efi e2fsprogs

#---------------------------------------------------------------------[ DISKS ]-

rc-update add swap boot

BOOTFS=vfat BOOTLOADER=grub DISKLABEL=gpt USE_EFI=1 \
	setup-disk -m sys /mnt

blkid | while read -r blk_ln; do
        eval "${blk_ln##*:}"
        [ "$TYPE" = "swap" ] && \
                printf 'UUID=%s\tswap\tswap\tdefaults\t0 0\n' "$UUID"
done >> /mnt/etc/fstab
